FROM alpine:3.24.1

ARG MINIO_VERSION=RELEASE.2025-04-22T22-12-26Z
ARG MINIO_SHA256=53e2a2cb16c5366ea6fbbc479c19ddb4c6a0948273e752f740fb1fbf27bb817c

RUN apk add --no-cache ca-certificates curl \
  && curl -fsSL \
    "https://github.com/minio/minio/releases/download/${MINIO_VERSION}/minio.linux-amd64.${MINIO_VERSION}" \
    -o /usr/local/bin/minio \
  && echo "${MINIO_SHA256}  /usr/local/bin/minio" | sha256sum -c - \
  && chmod 0755 /usr/local/bin/minio \
  && addgroup -S -g 1000 minio \
  && adduser -S -D -H -u 1000 -G minio minio \
  && mkdir -p /data \
  && chown -R minio:minio /data

USER 1000:1000

ENTRYPOINT ["/usr/local/bin/minio"]
