services:
  keycloak:
    environment:
      KC_HOSTNAME: ${CODESPACE_KEYCLOAK_URL}
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"
    volumes:
      - ./.codespaces/keycloak-realm.json:/opt/keycloak/data/import/projet-indiv26-realm.json:ro
