apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: projet-indiv26
type: Opaque
stringData:
  DATABASE_URL: "postgresql://app:REPLACE_ME@postgres:5432/projet_indiv26?schema=public"
