apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: projet-indiv26
data:
  PORT: "3000"
  KEYCLOAK_ISSUER: "https://auth.projet-indiv26.invalid/realms/projet-indiv26"
  KEYCLOAK_AUDIENCE: "api"
