apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy-api
  namespace: projet-indiv26
  labels:
    app.kubernetes.io/name: legacy-api
    app.kubernetes.io/part-of: projet-indiv26
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: legacy-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: legacy-api
        app.kubernetes.io/part-of: projet-indiv26
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: legacy-api
          image: projet-indiv26-legacy-api:m7-local
          imagePullPolicy: Never
          env:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: object-storage-credentials
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: object-storage-credentials
                  key: S3_SECRET_KEY
          envFrom:
            - configMapRef:
                name: legacy-api-config
            - secretRef:
                name: legacy-api-secrets
          ports:
            - name: http
              containerPort: 3099
          startupProbe:
            httpGet:
              path: /api/health/live
              port: http
            periodSeconds: 2
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /api/health/live
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: http
            periodSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
