apiVersion: v1
kind: Service
metadata:
  name: marketplace-service
  namespace: projet-indiv26
spec:
  selector:
    app.kubernetes.io/name: marketplace-service
  ports:
    - name: http
      port: 3102
      targetPort: http
