apiVersion: v1
kind: Secret
metadata:
  name: object-storage-credentials
  namespace: projet-indiv26
type: Opaque
stringData:
  MINIO_ROOT_USER: "REPLACE_ME"
  MINIO_ROOT_PASSWORD: "REPLACE_ME_WITH_RANDOM_ROOT_PASSWORD"
  S3_ACCESS_KEY: "REPLACE_ME"
  S3_SECRET_KEY: "REPLACE_ME_WITH_RANDOM_APP_SECRET"
