apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform
  namespace: projet-indiv26
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.projet-indiv26.local
        - api.projet-indiv26.local
        - auth.projet-indiv26.local
      secretName: platform-tls
  rules:
    - host: app.projet-indiv26.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  name: http
    - host: api.projet-indiv26.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  name: http
    - host: auth.projet-indiv26.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  name: http
