apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: projet-indiv26
type: Opaque
stringData:
  POSTGRES_DB: "projet_indiv26"
  POSTGRES_USER: "app"
  POSTGRES_PASSWORD: "REPLACE_ME"
